<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body">

        <div class="d-flex justify-content-center">
          <img src="/img/twitter_logo.png" />
        </div>

        <div class="row">
          <div class="col">
            <h2>Crie sua conta</h2>
          </div>
        </div>

        <div class="row">
          <div class="col">
            
            <form action="/registrar" method="POST">
              <div class="form-group mb-2">
                <input type="text" value="<?= $this->view->user['name'] ?>" class="form-control" placeholder="Nome" name="name" required>
              </div>
              
              <div class="form-group mb-2">
                <input type="email" value="<?= $this->view->user['email'] ?>" class="form-control" placeholder="E-mail" name="email" required>
              </div>

              <div class="form-group">
                <input type="password" value="<?= $this->view->user['password'] ?>" class="form-control" placeholder="Senha" name="password" required>
              </div>
              
              <div class="mt-4 mb-4">
                <small class="form-text">
                  Ao inscrever-se, você concorda com os Termos de Serviço e com as Políticas de Privacidade, incluindo o Uso de Cookies. Outras pessoas poderão encontrar você pelo e-mail ou número de telefone fornecido · Opções de Privacidade
                </small>
              </div>
              <button type="submit" class="btn btn-primary btn-block w-100">Inscrever-se</button>
              <?php if($this->view->errorRegister === true) { ?>

                <small class="text-danger">Preencha os campos corretamente ou verifique se já não possui uma conta neste email</small>

              <?php } ?>
            </form>

          </div>
        </div>

      </div>
    </div>
  </div>
</div>



    
  