<nav class="navbar navbar-expand-lg menu">
	<div class="container">
		<div class="navbar-nav">
			<a class="menuItem" href="/timeline">
				Home
			</a>

			<a class="menuItem" href="/sair">
				Sair
			</a>
			<img src="/img/twitter_logo.png" class="menuIco" />
		</div>
	</div>
</nav>

<div class="container mt-5">
	<div class="row pt-2">

		<div class="col-md-3">

			<div class="perfil">
				<div class="perfilTopo">

				</div>

				<div class="perfilPainel">

					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<span class="perfilPainelNome"><?= $_SESSION['name'] ?></span>
						</div>
					</div>

					<div class="row mb-2">

						<div class="col">
							<span class="perfilPainelItem">Tweets</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->amountTweets['tweets'] ?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguindo</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->amountFollows['follows'] ?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguidores</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->amountFollows['followers'] ?></span>
						</div>

					</div>

				</div>
			</div>

		</div>

		<div class="col-md-6">
			<div class="row mb-2">
				<div class="col tweetBox">
					<form action="/tweet" method="POST">
						<textarea class="form-control" id="tweetField" rows="3" name="tweet" required></textarea>
						<div class="col mt-2 d-flex justify-content-end">
							<button type="submit" class="btn btn-primary" id="btnTweet" disabled=false>Tweet</a>
						</div>

					</form>
				</div>
			</div>
			<?php foreach ($this->view->tweets as $tweet) { ?>
				<div class="row tweet">
					<div class="col">
						<p><strong><?= $tweet['name'] ?></strong> <small><span class="text text-muted">- <?= $tweet['data'] ?></span></p></small>
						<p><?= $tweet['tweet'] ?></p>

						<br />
						<form method="POST" action="/delete_tweet?id_tweet=<?= $tweet['id_tweet'] ?>">
							<?php if ($tweet['id_usuario'] === $_SESSION['id']) { ?>
								<div class="col d-flex justify-content-end">
									<button type="submit" class="btn btn-danger"><small>Remover</small></button>
								</div>
							<?php } ?>
						</form>
					</div>
				</div>
			<?php } ?>
		</div>

		<div class="col-md-3">
			<div class="quemSeguir">
				<span class="quemSeguirTitulo">Quem seguir</span><br />
				<hr />
				<a href="/who_follow" class="quemSeguirTxt">Procurar por pessoas conhecidas</a>
			</div>
		</div>
	</div>

	<div class="row mt-5">
		<nav aria-label="...">
			<ul class="pagination justify-content-center">
				<li class="page-item">
					<a class="page-link" href="?page=1" tabindex="-1">Primeira</a>
				</li>
				<?php for($i = 1; $i <= $this->view->amountPages; $i++) { ?>
					<li class="page-item <?= $this->view->pageActivated == $i ? 'active' : '' ?>">
						<a class="page-link" href="?page=<?= $i ?>"><?= $i ?></a>
					</li>
				<?php } ?>
				<li class="page-item">
					<a class="page-link" href="?page=<?= $this->view->amountPages ?>">Último</a>
				</li>
			</ul>
		</nav>
	</div>

</div>